In [1]:
import numpy as np

In [4]:
# np.ravel_multi_index(): 
# what is the index in flattened space defined by dims of your interested high dimensional index?

multi_index = (np.array([3, 2, 1]), np.array([4, 1, 7]))
dims = (4, 8)
flat_indices = np.ravel_multi_index(multi_index, dims, mode='clip', order='C')
# (3,4) -> 3*8+4=28; (2,1) -> 2*8+1=17; (1,7) -> 1*8+7=15
print(flat_indices)

[28 17 15]


In [9]:
# np.flipud(): a function flips an array in the up/down direction. This means it reverses the order of the rows of a given array, effectively flipping the array upside down.

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
flipped_array_2d = np.flipud(array_2d)

print("Original array:")
print(array_2d)

print("\nFlipped array:")
print(flipped_array_2d)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
array_1d = np.array([1, 2, 3, 4, 5])
flipped_array_1d = np.flipud(array_1d)

print("Original array:")
print(array_1d)

print("\nFlipped array:")
print(flipped_array_1d)

Original array:
[1 2 3 4 5]

Flipped array:
[5 4 3 2 1]


In [11]:
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])
flipped_array_3d = np.flipud(array_3d)

print("Original array:")
print(array_3d)

print("\nFlipped array:")
print(flipped_array_3d)

Original array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flipped array:
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
